import { useState } from "react";
import { Alert, Text, TextInput, View } from "react-native";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { router } from "expo-router";
import { Action, Heading, Notice, Page } from "../../components/Screen";
import { supabase } from "../../lib/supabase";
import { useTheme } from "../../lib/theme";
import { useQuery } from "@tanstack/react-query";
import { fetchCart } from "../../lib/data";
import { keys } from "../../lib/query";
import { formatNaira } from "../../lib/format";
const schema=z.object({customerName:z.string().trim().min(2,"Enter your name").max(120),customerEmail:z.string().trim().email("Enter a valid email").max(254),customerPhone:z.string().trim().min(7,"Enter a phone number").max(30),address:z.string().trim().min(5,"Enter your delivery address").max(300),city:z.string().trim().min(2,"Enter your city").max(100),state:z.string().trim().min(2,"Enter your state").max(100),notes:z.string().max(500).optional()});
export default function Checkout(){
  const t=useTheme();const[busy,setBusy]=useState(false);const cart=useQuery({queryKey:keys.cart,queryFn:fetchCart});const{control,handleSubmit,formState:{errors}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema),defaultValues:{notes:""}});
  const fields:[keyof z.infer<typeof schema>,string][]=[["customerName","Full name"],["customerEmail","Email"],["customerPhone","Phone"],["address","Delivery address"],["city","City"],["state","State"],["notes","Delivery notes (optional)"]];
  async function submit(values:z.infer<typeof schema>){if(!supabase)return;setBusy(true);try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sign in again to continue.");const siteUrl=process.env.EXPO_PUBLIC_SITE_URL;if(!siteUrl)throw new Error("The checkout service is not configured.");const response=await fetch(`${siteUrl.replace(/\/$/,"")}/api/mobile/checkout`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(values)});const result=await response.json();if(!response.ok)throw new Error(result.message??"Order could not be placed.");router.replace({pathname:"/checkout/success",params:{id:result.id,number:result.order_number,total:String(result.total_kobo),emailSent:String(result.email_sent)}});}catch(e){Alert.alert("Checkout could not be completed",e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
  const inputStyle={color:t.text,backgroundColor:t.surface,borderColor:t.border,borderWidth:1,padding:13,minHeight:48} as const;
  const subtotal=(cart.data?.items??[]).reduce((sum:number,item:any)=>sum+(item.product?.price_kobo+(item.variant?.price_modifier_kobo??0))*item.quantity,0);
  return <Page><Heading eyebrow="Almost home">Delivery details</Heading><Notice>Your order total and availability are confirmed securely when you place your order.</Notice><View style={{gap:7,padding:15,backgroundColor:t.surface,borderWidth:1,borderColor:t.border}}><Text style={{color:t.text}}>Subtotal  {cart.data?formatNaira(subtotal):"—"}</Text><Text style={{color:t.secondary}}>Delivery  {cart.data?.deliveryFee==null?"—":formatNaira(cart.data.deliveryFee)}</Text><Text style={{color:t.text,fontWeight:"600"}}>Estimated total  {cart.data?.deliveryFee==null?"—":formatNaira(subtotal+cart.data.deliveryFee)}</Text><Text style={{color:t.secondary,fontSize:12}}>The backend confirms the final amount.</Text></View><View style={{gap:14}}>{fields.map(([name,label])=><View key={name} style={{gap:5}}><Text style={{color:t.text,fontSize:13}}>{label}</Text><Controller control={control} name={name} render={({field:{onChange,onBlur,value}})=><TextInput value={value??""} onChangeText={onChange} onBlur={onBlur} placeholder={label} placeholderTextColor={t.secondary} keyboardType={name==="customerEmail"?"email-address":name==="customerPhone"?"phone-pad":"default"} multiline={name==="address"||name==="notes"} style={[inputStyle,{minHeight:name==="address"||name==="notes"?72:48,textAlignVertical:"top"}]}/>} />{errors[name]?<Text style={{color:t.danger,fontSize:12}}>{errors[name]?.message}</Text>:null}</View>)}</View><Action label={busy?"Placing your order…":"Place order"} disabled={busy||cart.isLoading||cart.isError||!cart.data?.items.length} onPress={handleSubmit(submit)}/></Page>;
}
