import { useEffect } from "react";
import { Alert, Text, TextInput, View } from "react-native";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Action, Heading, Notice, Page } from "../../components/Screen";
import { supabase } from "../../lib/supabase";
import { keys } from "../../lib/query";
import { useTheme } from "../../lib/theme";
const schema=z.object({full_name:z.string().trim().min(2,"Enter your name").max(120),phone:z.string().trim().max(30)});
export default function Profile(){const t=useTheme();const qc=useQueryClient();const q=useQuery({queryKey:keys.profile,queryFn:async()=>{if(!supabase)throw new Error();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data,error}=await supabase.from("profiles").select("full_name,email,phone").eq("id",user.id).maybeSingle();if(error)throw error;return data;}});const{control,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema),defaultValues:{full_name:"",phone:""}});useEffect(()=>{if(q.data)reset({full_name:q.data.full_name??"",phone:q.data.phone??""});},[q.data,reset]);async function save(values:z.infer<typeof schema>){try{if(!supabase)throw new Error();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error();const{error}=await supabase.from("profiles").update({full_name:values.full_name,phone:values.phone||null}).eq("id",user.id);if(error)throw error;await qc.invalidateQueries({queryKey:keys.profile});Alert.alert("Profile saved","Your contact details have been updated.");}catch{Alert.alert("Could not save profile","Please try again.");}}const style={color:t.text,backgroundColor:t.surface,borderWidth:1,borderColor:t.border,padding:12} as const;return <Page><Heading eyebrow="Your details">Profile</Heading>{q.isError?<Notice error>We could not load your profile.</Notice>:<><Text style={{color:t.secondary}}>Email: {q.data?.email??""}</Text><View style={{gap:14}}>{([ ["full_name","Full name"],["phone","Phone"] ] as const).map(([name,label])=><View key={name} style={{gap:5}}><Text style={{color:t.text}}>{label}</Text><Controller control={control} name={name} render={({field:{onChange,onBlur,value}})=><TextInput value={value} onChangeText={onChange} onBlur={onBlur} placeholder={label} placeholderTextColor={t.secondary} style={style}/>}/>{errors[name]?<Text style={{color:t.danger,fontSize:12}}>{errors[name]?.message}</Text>:null}</View>)}</View><Action label={isSubmitting?"Saving…":"Save profile"} onPress={handleSubmit(save)}/></>}</Page>;}
